# ~/.zshrc: executed by zsh(1) for interactive shells.
#
# zsh is the fallback shell here, not the daily driver (that is bash), so
# this file stays deliberately thin: it bootstraps Homebrew, pulls in the
# same POSIX login setup as bash, and hands off to ~/.config/zsh/init for
# the machine-specific environment generated by mkenv.
#
# Everything lives in ~/.zshrc rather than being split across
# ~/.zprofile: macOS terminals start login shells, but a zsh spawned from
# another shell is interactive-only, and that is exactly the case where
# node/python/PATH still need to work.

# If not running interactively, don't do anything.
[[ -o interactive ]] || return

# Homebrew: bring brew onto PATH before anything else needs it.
if ! (( $+commands[brew] )); then
    for _brew in /opt/homebrew/bin/brew /usr/local/bin/brew \
                     /home/linuxbrew/.linuxbrew/bin/brew; do
        if [ -x "$_brew" ]; then
            eval "$("$_brew" shellenv)"
            break
        fi
    done
    unset _brew
fi

# Login-shell environment (PATH additions, cargo env). POSIX sh only, so
# zsh can source it as-is.
if [ -f "$HOME/.profile" ]; then
    . "$HOME/.profile"
fi

# History: match the bash setup.
HISTFILE="$HOME/.zsh_history"
HISTSIZE=1000
SAVEHIST=2000
setopt append_history hist_ignore_all_dups hist_ignore_space share_history

# Prompt: same shape as the bash PS1.
PROMPT='[%F{green}%n@%m%f:%F{blue}%1~%f]%# '

case "$OSTYPE" in
    linux-gnu*)
        alias ls='ls --color=auto'
        alias grep='grep --color=auto'
        ;;
    darwin*|*bsd*)
        alias ls='ls -G'
        ;;
esac

alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'

# My zsh configuration (loads ~/.config/zsh/*).
if [ -f "$HOME/.config/zsh/init" ]; then
    . "$HOME/.config/zsh/init"
fi

# Local Variables:
# mode: shell-script
# End:
